// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateHeroHeroesPostData, CreateHeroHeroesPostErrors, CreateHeroHeroesPostResponses, DeleteHeroHeroesHeroIdDeleteData, DeleteHeroHeroesHeroIdDeleteErrors, DeleteHeroHeroesHeroIdDeleteResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, ReadHeroesHeroesGetData, ReadHeroesHeroesGetErrors, ReadHeroesHeroesGetResponses, ReadHeroHeroesHeroIdGetData, ReadHeroHeroesHeroIdGetErrors, ReadHeroHeroesHeroIdGetResponses, UpdateHeroHeroesHeroIdPatchData, UpdateHeroHeroesHeroIdPatchErrors, UpdateHeroHeroesHeroIdPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Read Heroes
 */
export const readHeroesHeroesGet = <ThrowOnError extends boolean = false>(options?: Options<ReadHeroesHeroesGetData, ThrowOnError>) => (options?.client ?? client).get<ReadHeroesHeroesGetResponses, ReadHeroesHeroesGetErrors, ThrowOnError>({ url: '/heroes/', ...options });

/**
 * Create Hero
 */
export const createHeroHeroesPost = <ThrowOnError extends boolean = false>(options: Options<CreateHeroHeroesPostData, ThrowOnError>) => (options.client ?? client).post<CreateHeroHeroesPostResponses, CreateHeroHeroesPostErrors, ThrowOnError>({
    url: '/heroes/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Hero
 */
export const deleteHeroHeroesHeroIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteHeroHeroesHeroIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteHeroHeroesHeroIdDeleteResponses, DeleteHeroHeroesHeroIdDeleteErrors, ThrowOnError>({ url: '/heroes/{hero_id}', ...options });

/**
 * Read Hero
 */
export const readHeroHeroesHeroIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadHeroHeroesHeroIdGetData, ThrowOnError>) => (options.client ?? client).get<ReadHeroHeroesHeroIdGetResponses, ReadHeroHeroesHeroIdGetErrors, ThrowOnError>({ url: '/heroes/{hero_id}', ...options });

/**
 * Update Hero
 */
export const updateHeroHeroesHeroIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateHeroHeroesHeroIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateHeroHeroesHeroIdPatchResponses, UpdateHeroHeroesHeroIdPatchErrors, ThrowOnError>({
    url: '/heroes/{hero_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
