// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HeroCreate
 */
export type HeroCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Secret Name
     */
    secret_name: string;
};

/**
 * HeroPublic
 */
export type HeroPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Id
     */
    id: number;
};

/**
 * HeroUpdate
 */
export type HeroUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Secret Name
     */
    secret_name?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadHeroesHeroesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/heroes/';
};

export type ReadHeroesHeroesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadHeroesHeroesGetError = ReadHeroesHeroesGetErrors[keyof ReadHeroesHeroesGetErrors];

export type ReadHeroesHeroesGetResponses = {
    /**
     * Response Read Heroes Heroes  Get
     *
     * Successful Response
     */
    200: Array<HeroPublic>;
};

export type ReadHeroesHeroesGetResponse = ReadHeroesHeroesGetResponses[keyof ReadHeroesHeroesGetResponses];

export type CreateHeroHeroesPostData = {
    body: HeroCreate;
    path?: never;
    query?: never;
    url: '/heroes/';
};

export type CreateHeroHeroesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateHeroHeroesPostError = CreateHeroHeroesPostErrors[keyof CreateHeroHeroesPostErrors];

export type CreateHeroHeroesPostResponses = {
    /**
     * Successful Response
     */
    200: HeroPublic;
};

export type CreateHeroHeroesPostResponse = CreateHeroHeroesPostResponses[keyof CreateHeroHeroesPostResponses];

export type DeleteHeroHeroesHeroIdDeleteData = {
    body?: never;
    path: {
        /**
         * Hero Id
         */
        hero_id: number;
    };
    query?: never;
    url: '/heroes/{hero_id}';
};

export type DeleteHeroHeroesHeroIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteHeroHeroesHeroIdDeleteError = DeleteHeroHeroesHeroIdDeleteErrors[keyof DeleteHeroHeroesHeroIdDeleteErrors];

export type DeleteHeroHeroesHeroIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadHeroHeroesHeroIdGetData = {
    body?: never;
    path: {
        /**
         * Hero Id
         */
        hero_id: number;
    };
    query?: never;
    url: '/heroes/{hero_id}';
};

export type ReadHeroHeroesHeroIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadHeroHeroesHeroIdGetError = ReadHeroHeroesHeroIdGetErrors[keyof ReadHeroHeroesHeroIdGetErrors];

export type ReadHeroHeroesHeroIdGetResponses = {
    /**
     * Successful Response
     */
    200: HeroPublic;
};

export type ReadHeroHeroesHeroIdGetResponse = ReadHeroHeroesHeroIdGetResponses[keyof ReadHeroHeroesHeroIdGetResponses];

export type UpdateHeroHeroesHeroIdPatchData = {
    body: HeroUpdate;
    path: {
        /**
         * Hero Id
         */
        hero_id: number;
    };
    query?: never;
    url: '/heroes/{hero_id}';
};

export type UpdateHeroHeroesHeroIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateHeroHeroesHeroIdPatchError = UpdateHeroHeroesHeroIdPatchErrors[keyof UpdateHeroHeroesHeroIdPatchErrors];

export type UpdateHeroHeroesHeroIdPatchResponses = {
    /**
     * Successful Response
     */
    200: HeroPublic;
};

export type UpdateHeroHeroesHeroIdPatchResponse = UpdateHeroHeroesHeroIdPatchResponses[keyof UpdateHeroHeroesHeroIdPatchResponses];
